name: bus42app
description: Bus42.info

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http:
  path_provider:
  shared_preferences:
  fluttertoast:
  sticky_headers:
  sticky_and_expandable_list:
  pull_to_refresh:

  # cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/drawer.jpg